CREATE PROCEDURE SP_MOSTRARTABLAEMPLEADOS
AS
SELECT * FROM Empleados
GO

EXEC SP_MOSTRARTABLAEMPLEADOS


--CREATE PROCEDURE SP_MOSTRARTABLAFECHAEMPLEADO
--AS
--SELECT * FROM Fecha_Empleado
--GO

EXEC SP_MOSTRARTABLAFECHAEMPLEADO
